In [1]:
import torch
import numpy as np

In [2]:
a = [np.array([1,2,3]),np.array([1,2,3]),np.array([1,2,3])]


In [4]:
b = torch.tensor(a)

In [7]:
c = np.array(a)
print(a)

[array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3])]


In [28]:
b = torch.tensor([2,3,4,5])
b = b.unsqueeze(0)
print(b.shape)
a = torch.empty(0,0)
print(a.shape)





torch.Size([1, 4])
torch.Size([0, 0])


In [34]:
a = b
print(a.shape)
print(a)

torch.Size([1, 4])
tensor([[2, 3, 4, 5]])


In [18]:
a = torch.cat((a,b),dim=0)
print(a)

tensor([2., 3., 4., 5., 2., 3., 4., 5., 2., 3., 4., 5.])


In [43]:
tensor = torch.tensor([1,2,3,4]).tolist()
other_tensor = torch.tensor([2,2,4,5]).tolist()
lista = [tensor,other_tensor]

print(lista)

[[1, 2, 3, 4], [2, 2, 4, 5]]


In [48]:

a = torch.empty((11,12,12))
a.shape

torch.Size([11, 12, 12])

In [52]:
b = torch.rand_like(a)
c = torch.rand_like(a)

In [55]:
print(b.shape)
c = torch.cat((b,c))

print(c.shape)

torch.Size([11, 12, 12])
torch.Size([33, 12, 12])


In [61]:
a = torch.zeros(10,10)
c = [9,2,3]

In [66]:
actions = np.eye(10, dtype=np.float32)
actions[np.array(c)]

actions = np.reshape(actions, [-1, self.max_moves,
                                       self.action_dim])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [69]:
from torch.nn.functional import one_hot

In [94]:
sample = torch.from_numpy(np.random.random_integers(0,132,(22,13)))
print(torch.max(sample))

tensor(132, dtype=torch.int32)


C:\Users\Usuario\AppData\Local\Temp\ipykernel_18368\1487824285.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 132 + 1) instead
  sample = torch.from_numpy(np.random.random_integers(0,132,(22,13)))


In [95]:
one_hot_encoded = torch.nn.functional.one_hot(sample.to(torch.int64), 132)
print(one_hot_encoded)

RuntimeError: Class values must be smaller than num_classes.

In [97]:
np.random.random_integers(0,1,5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18368\3345052295.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  np.random.random_integers(0,1,5)


array([0, 0, 0, 1, 0])